name: backend-ci

on:
  push:
    paths:
      - 'wagnerfit-backend/**'
  pull_request:
    paths:
      - 'wagnerfit-backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wagnerfit-backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          ruff .
          black --check .
          isort --check-only .
      - name: Type check
        run: mypy app
      - name: Tests
        run: pytest -q
